name: Web

on:
  push:
    branches: [ "develop", "edge", "release" ]
  pull_request:
    branches: [ "develop" ]

  workflow_dispatch:

env:
  VXT_VERSION: 1.3.0
  ODIN_VERSION: dev-2025-02
  CONTENT: "svardos.img svardos_hd.img elks_hd.img"

jobs:
  web-build:
    name: Web
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x

      - name: Setup
        run: |
          sudo apt-get update
          sudo apt-get install lld coffeescript
          rm -rf odin; mkdir odin
          curl -L -o odin.zip https://github.com/odin-lang/Odin/releases/download/${ODIN_VERSION}/odin-linux-amd64-${ODIN_VERSION}.zip && unzip odin.zip
          curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default && unzip butler.zip -d butler
          echo "${GITHUB_WORKSPACE}/butler" >> $GITHUB_PATH
          echo "${GITHUB_WORKSPACE}/odin-linux-amd64-${ODIN_VERSION}" >> $GITHUB_PATH
          
      - name: Setup (RetroArch)
        run: |
          git clone -b virtualxt https://github.com/virtualxt/RetroArch
          curl -L -o RetroArch.7z https://buildbot.libretro.com/nightly/emscripten/RetroArch.7z && 7z x RetroArch.7z
          
      - name: Setup (Emscripten)
        run: |
          git clone https://github.com/emscripten-core/emsdk
          cd emsdk
          ./emsdk install 3.1.46
          ./emsdk activate 3.1.46

      - name: Test
        run: make tests

      - name: Build (VirtualXT)
        run: |
          ODIN_TARGET=freestanding_wasm32 make object
          source emsdk/emsdk_env.sh && emar rcs virtualxt_libretro_emscripten.bc virtualxt_libretro.wasm.o          

      - name: Build (RetroArch)
        run: |
          cp virtualxt_libretro_emscripten.bc RetroArch/libretro_emscripten.bc
          cd RetroArch
          source ../emsdk/emsdk_env.sh && emmake make -f Makefile.emscripten LIBRETRO=virtualxt -j all
          cp virtualxt_libretro.{js,wasm} pkg/emscripten/libretro
          mkdir -p pkg/emscripten/libretro/assets/cores/VirtualXT
          cp -r ../retroarch/assets/frontend pkg/emscripten/libretro/assets
          cp -r ../retroarch/media pkg/emscripten/libretro

      - name: Content
        run: |
          CONTENT_DEST=RetroArch/pkg/emscripten/libretro/assets/cores/VirtualXT
          for FILE in ${CONTENT}; do
            cp boot/${FILE} ${CONTENT_DEST}
            echo ${FILE} >> ${CONTENT_DEST}/.index
          done
          echo >> ${CONTENT_DEST}/../.index
          echo VirtualXT >> ${CONTENT_DEST}/../.index-dirs
          cd RetroArch/pkg/emscripten/libretro
          chmod +x indexer
          cd assets/cores
          ../../indexer > .index-xhr
          
      #- name: Deploy
      #  env:
      #    BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
      #  run: |
      #    if [[ $GITHUB_REF_NAME =~ ^(edge)$ ]]; then
      #      butler login
      #      butler push RetroArch/pkg/emscripten/libretro phix/virtualxt:web-${GITHUB_REF_NAME} --userversion ${VXT_VERSION}-${GITHUB_RUN_ID}
      #    fi

      - name: Deploy2
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
        run: |
          if [[ $GITHUB_REF_NAME =~ ^(develop)$ ]]; then
            butler login
            butler push RetroArch/pkg/emscripten/libretro phix/web-test:web-odin-${GITHUB_REF_NAME} --userversion ${VXT_VERSION}-${GITHUB_RUN_ID}
          fi
